name: 'Trace Workflow Actions'
description: 'publishes execution traces of workflow actions.'
inputs:
  github-commit-sha:
    default: "${{ github.event.pull_request.head.sha || github.sha }}"
  github-owner:
    default: "${{ github.repository_owner }}"
  github-repo:
    default: "${{ github.repository }}"
  github-run-id:
    default: "${{ github.event.workflow_run.id }}"
  github-token:
    default: "${{ github.token }}"
runs:
  using: 'docker'
  image: "docker://ghcr.io/freckle/trace-workflow-action-image:43355e9beffbab8294afac35d8c58a9ca1e89658"
  env:
    GITHUB_COMMIT_SHA: ${{ inputs.github-commit-sha }}
    GITHUB_OWNER: ${{ inputs.github-owner }}
    GITHUB_REPO: ${{ inputs.github-repo }}
    GITHUB_RUN_ID: ${{ inputs.github-run-id }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
