services:
  otel-collector:
    image: 853032795538.dkr.ecr.us-east-1.amazonaws.com/frontrow/opentelemetry-collector:0.97.0
    platform: "linux/amd64"
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-config.yaml:/config.yaml:ro
      - ./file-exporter:/file-exporter:rwz
    environment:
      DD_API_KEY: $DD_API_KEY
      OTLP_ENV: $OTLP_ENV
      OTLP_SERVICE: $OTLP_SERVICE
      OTLP_VERSION: $OTLP_VERSION
    command: ["--config", "/config.yaml"]

  # viewer:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  #     - "4317:4317"
  #     - "4318:4318"
  #     - "5778:5778"
  #     - "9411:9411"
