services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-config.yaml:/config.yaml:ro
      - ./file-exporter:/file-exporter:rwz
    environment:
      DD_API_KEY: $DD_API_KEY
      OTLP_ENV: $OTLP_ENV
      OTLP_SERVICE: $OTLP_SERVICE
      OTLP_VERSION: $OTLP_VERSION
    command: ["--config", "/config.yaml"]
