extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s
  attributes/tags:
    actions:
      - key: env
        value: $OTLP_ENV
        action: upsert
      - key: service
        value: $OTLP_SERVICE
        action: upsert
      - key: version
        value: $OTLP_VERSION
        action: upsert
      - key: otlp
        value: true
        action: insert

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: $DD_API_KEY

  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/tags,batch]
      exporters: [datadog, logging]
  extensions: [health_check]
