resolver: lts-20.18
extra-deps:
  - github-0.29
  - hs-opentelemetry-api-0.1.0.0
  - hs-opentelemetry-exporter-otlp-0.0.1.5
  - hs-opentelemetry-otlp-0.0.1.0
  - hs-opentelemetry-propagator-b3-0.0.1.1
  - hs-opentelemetry-propagator-w3c-0.0.1.3
  - hs-opentelemetry-sdk-0.0.3.6
  - thread-utils-context-0.3.0.4
  - thread-utils-finalizers-0.1.1.0
