name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test-setup:
    runs-on: ubuntu-latest
    container:
      image: 'debian:bullseye'
      volumes:
        - 'config_volume:/config'
    steps:
      - run: echo "testing 123 $(date)" > /config/default.yaml
  test:
    runs-on: ubuntu-latest
    needs:
      - test-setup
    services:
      otel-collector:
        image: otel/opentelemetry-collector-contrib:0.97.0
        ports:
          - "4317:4317"
          - "4318:4318"
        volumes:
          - 'config_volume:/config'
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    container:
      image: 'debian:bullseye'
      volumes:
        - 'config_volume:/config'

    steps:
      - run: ls /config
      - run: cat /config/default.yaml
      # - uses: .
  # test:
  #   services:
  #     otel-collector:
  #       image: otel/opentelemetry-collector-contrib:0.97.0
  #       ports:
  #         - "4317:4317"
  #         - "4318:4318"
  #       volumes:
  #         - ./otel-config.yaml:/config.yaml
  #         - ./file-exporter:/file-exporter
  #       environment:
  #         DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  #       command: ["--config", "/config.yaml"]
  #   run:
  #     - uses: .

# FROM otel/opentelemetry-collector-contrib:0.97.0
# COPY config /config
# CMD ["--config", "/config/default.yaml"]
