name: CI

on:
  pull_request:
  push:
    branches: main

permissions:
  packages: write
  contents: write
  attestations: write
  id-token: write
  actions: write
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo "tag=$TAG" >>"$GITHUB_OUTPUT"
        env:
          TAG: ${{ github.event.pull_request.head.sha || github.sha }}
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}

  otel-image:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: ghcr.io/freckle/trace-workflow-action-otel-image
          tags: |
            type=edge,branch=main
            type=raw,value=${{ needs.setup.outputs.tag }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: otel-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  trace-workflow-action-image:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: ghcr.io/freckle/trace-workflow-action-image
          tags: |
            type=edge,branch=main
            type=raw,value=${{ needs.setup.outputs.tag }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # test:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - setup
  #     - otel-image
  #   services:
  #     otel-collector:
  #       image: "ghcr.io/freckle/trace-workflow-action-otel-image:${{needs.setup.outputs.tag}}"
  #       ports:
  #         - "4317:4317"
  #         - "4318:4318"
  #       env:
  #         DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./
  #       # with:
  #       #   workflow-action-image-tag: ${{ needs.setup.outputs.tag }}
